#ifndef CONFIG_H_
#define CONFIG_H_

	// Команды UART
	#define COM_GET_TIME				1
	#define COM_SET_TIME				2
	#define COM_GET_DATE				3
	#define COM_SET_DATE				4
	#define COM_GET_LIGHT_SALOON		5
	#define COM_SET_LIGHT_SALOON		6
	#define COM_GET_LIGHT_BRIGHT		7
	#define COM_SET_LIGHT_BRIGHT		8
	#define COM_GET_LIGHT_NEON			9
	#define COM_SET_LIGHT_NEON			10
	#define COM_GET_LIGHT_NEON_BRIGHT	11
	#define COM_SET_LIGHT_NEON_BRIGHT	12
	#define COM_GET_FOG					13
	#define COM_SET_FOG					14
	#define COM_GET_FOG_BRIGHT			15
	#define COM_SET_FOG_BRIGHT			16
	#define COM_GET_FAN					17
	#define COM_SET_FAN					18
	#define COM_GET_FAN_AUTO			19
	#define COM_SET_FAN_AUTO			20
	#define COM_GET_AUTO_MIRROR_HEATING	21
	#define COM_SET_AUTO_MIRROR_HEATING	22
	#define COM_SET_AUTO_MIRROR_TIME	23
	#define COM_GET_MIRROR_HEATING		24
	#define COM_SET_MIRROR_HEATING		25
	#define COM_GET_WINDOW_HEATING		26
	#define COM_SET_WINDOW_HEATING		27
	#define COM_GET_TEMP				28
	#define COM_SET_TEMP				29
	#define COM_SET_LOWPOWER_MODE		30
	#define COM_SET_NORMAL_MODE			31
	#define COM_SET_ENGINE_WORK			32
	#define COM_SET_ENGINE_NOT_WORK		33
	#define COM_GET_AUTO_HEADLIGHT		34
	#define COM_SET_AUTO_HEADLIGHT		35
	#define COM_SET_HEADLIGHT_TIME_ON	36
	#define COM_SET_HEADLIGHT_TIME_OFF	37
	#define COM_GET_VERSION				38
	#define COM_SET_DRIVER_INSIDE		39
	#define COM_GET_AUTO_DAYLIGHT		40
	#define COM_SET_AUTO_DAYLIGHT		41
	#define COM_GET_FERNS_FOG			42
	#define COM_SET_FERNS_FOG			43
	#define COM_GET_DIBILMODE			44
	#define COM_SET_DIBILMODE			45
	#define COM_GET_DRIVE_MODE_VALUE	46
	#define COM_GET_AUTOSTOP_ENGINE		47
	#define COM_SET_AUTOSTOP_ENGINE		48

	// Команды I2C
	#define COM_I2C_SET_ACC				1
	#define COM_I2C_GET_RFID			2
	#define COM_I2C_SET_MANUAL_START	3
	#define COM_I2C_SET_ENGINE_STOP		4
	#define COM_I2C_SET_STARTER			5
	#define COM_I2C_GET_AUTHORIZED		6
	#define COM_I2C_SET_ADD_RFID		7
	#define COM_I2C_SET_ENGINE_START	8
	#define COM_I2C_SET_DRIVER_OUT		9
	#define COM_I2C_GET_TEMP			10

	// Drive value bits
	#define DRV_BIT_HEADLIGHT_ON		0b00000001
	#define DRV_BIT_FOG_ON				0b00000010
	#define DRV_BIT_FOG_FERNS_ON		0b00000100
	#define DRV_BIT_MIRRORS_HEATING_ON	0b00001000
	#define DRV_BIT_MIRRORS_HEATING_OFF	0b00010000

#endif